name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: rustup install nightly
      run: rustup default nightly
      run: rustup target add riscv64imac-unknown-none-elf
      run: cargo build --verbose --target riscv64imac-unknown-none-elf
    - name: Run tests
      run: rustup install nightly
      run: rustup default nightly
      run: rustup target add riscv64imac-unknown-none-elf
      run: cargo test --verbose --target riscv64imac-unknown-none-elf
